'use server';
import {cookies} from 'next/headers';import {redirect} from 'next/navigation';import {revalidatePath} from 'next/cache';import {Prisma} from '@prisma/client';
import {db} from './db';import {hashPassword,verifyPassword,createSession,requireAccount,tokenHash} from './auth';import {TYPES,STATUSES} from './constants';
function text(f:FormData,k:string,max=1000){const v=f.get(k);return typeof v==='string'?v.trim().slice(0,max):'';}
function secret(f:FormData,k:string){const v=f.get(k);return typeof v==='string'?v.slice(0,200):'';}
function id(f:FormData,k='id'){const v=Number(f.get(k));if(!Number.isInteger(v)||v<=0)throw new Error('Registro inválido.');return v;}
function cents(f:FormData,k:string){const raw=text(f,k).replace(',','.');const n=raw?Number(raw):0;if(!Number.isFinite(n)||n<0||n>100000000)throw new Error('Valor inválido.');return Math.round(n*100);}
function dateValue(f:FormData,k:string){const v=text(f,k);if(!v)return null;const d=new Date(v+'T12:00:00Z');if(isNaN(d.getTime()))throw new Error('Data inválida.');return d;}
function emailValue(f:FormData){const v=text(f,'email',160).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw new Error('Informe um e-mail válido.');return v;}
function required(v:string,label:string){if(!v)throw new Error(label+' é obrigatório.');return v;}
function errorMessage(e:unknown){if(e instanceof Prisma.PrismaClientKnownRequestError){if(e.code==='P2002')return 'Já existe um registro com esse e-mail, patrimônio ou número de série.';if(e.code==='P2025')return 'O registro mudou. Atualize a página e tente novamente.';}return e instanceof Error&&!e.message.includes('prisma.')&&!e.message.includes('Invocation')?e.message:'Não foi possível concluir. Tente novamente.';}
const refresh=()=>revalidatePath('/','layout');
export async function login(f:FormData){try{const email=text(f,'email',160).toLowerCase();const password=secret(f,'password');const account=await db.adm.findUnique({where:{email}});const locked=account?.lockedUntil&&account.lockedUntil.getTime()>Date.now();if(locked)throw new Error('Muitas tentativas. Aguarde 15 minutos antes de tentar novamente.');const valid=account&&verifyPassword(password,account.password);if(!account?.active||!valid){if(account){const failed=account.lockedUntil&&account.lockedUntil.getTime()<=Date.now()?1:account.failedAttempts+1;await db.adm.update({where:{email},data:{failedAttempts:failed,lockedUntil:failed>=5?new Date(Date.now()+15*60*1000):null}});}else{hashPassword(password||'invalid');}throw new Error('E-mail ou senha incorretos.');}await db.adm.update({where:{email},data:{failedAttempts:0,lockedUntil:null,...(!account.password.startsWith('scrypt:')?{password:hashPassword(password),passwordChangeRequired:true}:{})}});await db.session.deleteMany({where:{expiresAt:{lt:new Date()}}});await createSession(email);}catch(e){return {error:errorMessage(e)}}redirect('/');}
export async function setup(f:FormData){try{if(await db.adm.count())throw new Error('O primeiro acesso já foi configurado.');const name=required(text(f,'name',100),'Nome');const email=emailValue(f);const password=secret(f,'password');if(password.length<10)throw new Error('Use uma senha com pelo menos 10 caracteres.');await db.$transaction(async tx=>{if(process.env.SGEE_LOCAL_PREVIEW!=='true')await tx.$executeRawUnsafe('LOCK TABLE "Adm" IN EXCLUSIVE MODE');if(await tx.adm.count())throw new Error('O primeiro acesso já foi configurado.');await tx.adm.create({data:{email,name,password:hashPassword(password)}});});await createSession(email);}catch(e){return {error:errorMessage(e)}}redirect('/');}
export async function logout(){const token=(await cookies()).get('sgee_session')?.value;if(token)await db.session.deleteMany({where:{tokenHash:tokenHash(token)}});(await cookies()).delete('sgee_session');redirect('/login');}
export async function saveEquipment(f:FormData){try{const actor=await requireAccount(true);const equipmentId=text(f,'id')?id(f):null;const name=required(text(f,'nome',120),'Nome');const tipo=text(f,'tipo');const status=text(f,'status')||'disponível';if(!TYPES.includes(tipo)||!STATUSES.includes(status))throw new Error('Tipo ou situação inválidos.');const userId=text(f,'userId')?id(f,'userId'):null;if(status!=='em uso'&&userId)throw new Error('Selecione Em uso para vincular um responsável.');if(status==='em uso'&&!userId)throw new Error('Selecione um responsável para o equipamento em uso.');if(status==='manutenção')throw new Error('Registre uma manutenção na seção Manutenção.');const data={nome:name,tipo,status,descricao:text(f,'descricao',4000),assetTag:text(f,'assetTag',80)||null,serial:text(f,'serial',120)||null,brand:text(f,'brand',80),model:text(f,'model',100),location:text(f,'location',120),purchaseDate:dateValue(f,'purchaseDate'),warrantyUntil:dateValue(f,'warrantyUntil'),purchaseCents:cents(f,'purchaseCents'),userId};
await db.$transaction(async tx=>{let previous=null;if(equipmentId){previous=await tx.equipamento.findUnique({where:{id:equipmentId},include:{user:true}});if(!previous||previous.archivedAt)throw new Error('Equipamento não encontrado.');if(previous.status==='manutenção')throw new Error('Conclua a manutenção antes de alterar o equipamento.');}
const user=userId?await tx.user.findUnique({where:{id:userId}}):null;if(userId&&!user?.active)throw new Error('O responsável precisa estar ativo.');const item=equipmentId?await tx.equipamento.update({where:{id:equipmentId},data}):await tx.equipamento.create({data});if(!previous||previous.userId!==userId||previous.status!==status)await tx.movement.create({data:{equipmentId:item.id,kind:!previous?'cadastro':status==='baixado'?'baixa':previous.userId&&userId?'transferência':userId?'entrega':'devolução',fromName:previous?.user?.name??null,toName:user?.name??null,note:text(f,'note',1000),actor:actor.name}});await tx.auditLog.create({data:{actor:actor.email,action:equipmentId?'Equipamento atualizado':'Equipamento cadastrado',target:name}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function archiveEquipment(f:FormData){try{const actor=await requireAccount(true);await db.$transaction(async tx=>{const item=await tx.equipamento.findUnique({where:{id:id(f)}});if(!item||item.archivedAt)throw new Error('Equipamento não encontrado.');if(item.userId||item.status==='manutenção')throw new Error('Devolva o equipamento e conclua as manutenções antes de arquivar.');await tx.equipamento.update({where:{id:item.id},data:{archivedAt:new Date(),status:'baixado'}});await tx.auditLog.create({data:{actor:actor.email,action:'Equipamento arquivado',target:item.nome}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function restoreEquipment(f:FormData){try{const actor=await requireAccount(true);const item=await db.equipamento.update({where:{id:id(f)},data:{archivedAt:null,status:'disponível',userId:null}});await db.auditLog.create({data:{actor:actor.email,action:'Equipamento restaurado',target:item.nome}});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function savePerson(f:FormData){try{const actor=await requireAccount(true);const personId=text(f,'id')?id(f):null;const data={name:required(text(f,'name',100),'Nome'),email:emailValue(f),department:text(f,'department',100),location:text(f,'location',120)};const item=personId?await db.user.update({where:{id:personId},data}):await db.user.create({data});await db.auditLog.create({data:{actor:actor.email,action:personId?'Responsável atualizado':'Responsável cadastrado',target:item.name}});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function togglePerson(f:FormData){try{const actor=await requireAccount(true);await db.$transaction(async tx=>{const item=await tx.user.findUnique({where:{id:id(f)},include:{equipamentos:true}});if(!item)throw new Error('Responsável não encontrado.');if(item.active&&item.equipamentos.length)throw new Error('Devolva ou transfira os equipamentos antes de desativar o responsável.');await tx.user.update({where:{id:item.id},data:{active:!item.active}});await tx.auditLog.create({data:{actor:actor.email,action:item.active?'Responsável desativado':'Responsável reativado',target:item.name}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function moveEquipment(f:FormData){try{const actor=await requireAccount(true);const equipmentId=id(f,'equipmentId');const targetId=text(f,'userId')?id(f,'userId'):null;await db.$transaction(async tx=>{const item=await tx.equipamento.findUnique({where:{id:equipmentId},include:{user:true}});if(!item||item.archivedAt||['manutenção','baixado'].includes(item.status))throw new Error('Este equipamento não pode ser movimentado.');if(item.userId===targetId)throw new Error('Selecione um responsável diferente ou registre a devolução.');const user=targetId?await tx.user.findUnique({where:{id:targetId}}):null;if(targetId&&!user?.active)throw new Error('Responsável indisponível.');const result=await tx.equipamento.updateMany({where:{id:equipmentId,userId:item.userId,status:item.status},data:{userId:targetId,status:targetId?'em uso':'disponível'}});if(result.count!==1)throw new Error('O equipamento foi alterado por outra pessoa. Atualize e tente novamente.');await tx.movement.create({data:{equipmentId,kind:item.userId&&targetId?'transferência':targetId?'entrega':'devolução',fromName:item.user?.name??null,toName:user?.name??null,note:text(f,'note',1000),actor:actor.name}});await tx.auditLog.create({data:{actor:actor.email,action:'Movimentação registrada',target:item.nome}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function saveMaintenance(f:FormData){try{const actor=await requireAccount(true);await db.$transaction(async tx=>{const item=await tx.equipamento.findUnique({where:{id:id(f,'equipmentId')},include:{user:true}});if(!item||item.archivedAt||['manutenção','baixado'].includes(item.status))throw new Error('O equipamento está indisponível para manutenção.');const changed=await tx.equipamento.updateMany({where:{id:item.id,status:item.status,userId:item.userId},data:{status:'manutenção',userId:null}});if(changed.count!==1)throw new Error('Equipamento alterado. Atualize a página.');await tx.maintenance.create({data:{equipmentId:item.id,title:required(text(f,'title',150),'Título'),description:text(f,'description',4000),vendor:text(f,'vendor',120),dueAt:dateValue(f,'dueAt'),costCents:cents(f,'costCents')}});await tx.movement.create({data:{equipmentId:item.id,kind:'manutenção',fromName:item.user?.name??null,toName:'Manutenção',note:text(f,'title'),actor:actor.name}});await tx.auditLog.create({data:{actor:actor.email,action:'Manutenção aberta',target:item.nome}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function updateMaintenance(f:FormData){try{const actor=await requireAccount(true);const state=text(f,'status');if(!['em andamento','concluída'].includes(state))throw new Error('Situação inválida.');await db.$transaction(async tx=>{const m=await tx.maintenance.findUnique({where:{id:id(f)},include:{equipment:true}});if(!m||m.completedAt)throw new Error('Manutenção já encerrada.');await tx.maintenance.update({where:{id:m.id},data:{status:state,costCents:cents(f,'costCents'),completedAt:state==='concluída'?new Date():null}});if(state==='concluída'){await tx.equipamento.update({where:{id:m.equipmentId},data:{status:'disponível',userId:null}});await tx.movement.create({data:{equipmentId:m.equipmentId,kind:'retorno de manutenção',fromName:'Manutenção',toName:'Estoque',actor:actor.name,note:m.title}});}await tx.auditLog.create({data:{actor:actor.email,action:'Manutenção '+state,target:m.equipment.nome}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function saveAccount(f:FormData){try{const actor=await requireAccount(true,true);const email=emailValue(f);const role=text(f,'role');if(!['ADMIN','OPERATOR','VIEWER'].includes(role))throw new Error('Perfil inválido.');const password=secret(f,'password');if(password.length<10)throw new Error('Use uma senha com pelo menos 10 caracteres.');await db.adm.create({data:{email,name:required(text(f,'name',100),'Nome'),role,password:hashPassword(password)}});await db.auditLog.create({data:{actor:actor.email,action:'Conta criada',target:email}});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function toggleAccount(f:FormData){try{const actor=await requireAccount(true,true);const email=text(f,'email');if(email===actor.email)throw new Error('Você não pode desativar sua própria conta.');await db.$transaction(async tx=>{const account=await tx.adm.findUnique({where:{email}});if(!account)throw new Error('Conta não encontrada.');if(account.active&&account.role==='ADMIN'&&(await tx.adm.count({where:{active:true,role:'ADMIN'}}))<=1)throw new Error('Mantenha pelo menos um administrador ativo.');await tx.adm.update({where:{email},data:{active:!account.active}});await tx.session.deleteMany({where:{accountEmail:email}});await tx.auditLog.create({data:{actor:actor.email,action:account.active?'Conta desativada':'Conta reativada',target:email}});});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function changePassword(f:FormData){try{const actor=await requireAccount();if(!verifyPassword(secret(f,'currentPassword'),actor.password))throw new Error('Senha atual incorreta.');const next=secret(f,'password');if(next.length<10)throw new Error('Use pelo menos 10 caracteres.');if(next!==secret(f,'confirmPassword'))throw new Error('As senhas não coincidem.');await db.adm.update({where:{email:actor.email},data:{password:hashPassword(next),passwordChangeRequired:false}});await db.session.deleteMany({where:{accountEmail:actor.email}});await createSession(actor.email);return {ok:true};}catch(e){return {error:errorMessage(e)}}}
export async function saveSettings(f:FormData){try{await requireAccount(true,true);await db.appSettings.upsert({where:{id:1},create:{company:required(text(f,'company',80),'Nome da empresa')},update:{company:required(text(f,'company',80),'Nome da empresa')}});refresh();return {ok:true};}catch(e){return {error:errorMessage(e)}}}




