import {redirect} from 'next/navigation';import {db} from './db';import {currentAccount} from './auth';
export async function getWorkspace(){const account=await currentAccount();if(!account)redirect('/login');const [equipment,people,movements,maintenance,audit,accounts,settings]=await Promise.all([db.equipamento.findMany({include:{user:true},orderBy:{id:'desc'}}),db.user.findMany({orderBy:{name:'asc'}}),db.movement.findMany({include:{equipment:{select:{nome:true,assetTag:true}}},orderBy:{id:'desc'},take:1000}),db.maintenance.findMany({include:{equipment:{select:{nome:true,assetTag:true}}},orderBy:{id:'desc'}}),db.auditLog.findMany({orderBy:{id:'desc'},take:50}),account.role==='ADMIN'?db.adm.findMany({select:{email:true,name:true,role:true,active:true},orderBy:{name:'asc'}}):[],db.appSettings.findUnique({where:{id:1}})]);return JSON.parse(JSON.stringify({equipment,people,movements,maintenance,audit,accounts,localPreview:process.env.SGEE_LOCAL_PREVIEW==='true',company:settings?.company??'SGEE',account:{email:account.email,name:account.name,role:account.role,passwordChangeRequired:account.passwordChangeRequired}})) as Workspace;}
export type Equipment={id:number;nome:string;tipo:string;status:string;descricao:string;userId:number|null;user:{id:number;name:string}|null;assetTag:string|null;serial:string|null;brand:string;model:string;location:string;purchaseDate:string|null;warrantyUntil:string|null;purchaseCents:number;createdAt:string;updatedAt:string;archivedAt:string|null};
export type Person={id:number;name:string;email:string;department:string;location:string;active:boolean;createdAt:string};
export type Movement={id:number;equipmentId:number;kind:string;fromName:string|null;toName:string|null;note:string;actor:string;createdAt:string;equipment:{nome:string;assetTag:string|null}};
export type Maintenance={id:number;equipmentId:number;title:string;description:string;vendor:string;status:string;dueAt:string|null;costCents:number;createdAt:string;completedAt:string|null;equipment:{nome:string;assetTag:string|null}};
export type Workspace={localPreview:boolean;equipment:Equipment[];people:Person[];movements:Movement[];maintenance:Maintenance[];audit:{id:number;actor:string;action:string;target:string;createdAt:string}[];accounts:{email:string;name:string;role:string;active:boolean}[];company:string;account:{email:string;name:string;role:string;passwordChangeRequired:boolean}};



