// src/app/layout.tsx

import { GeistSans } from 'geist/font/sans';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-theme="light" className='bg-color1'>
      <body className={GeistSans.className}>
        {children}
      </body>
    </html>
  );
}


