require('dotenv').config({path:'.env',quiet:true});
const fs=require('node:fs');const path=require('node:path');const {randomUUID,createHash}=require('node:crypto');const {Client}=require('pg');
const url=new URL(process.env.POSTGRES_URL_NON_POOLING);url.searchParams.set('sslmode','verify-full');
const client=new Client({connectionString:url.toString(),connectionTimeoutMillis:15000});
(async()=>{try{await client.connect();await client.query('SELECT pg_advisory_lock(61008004)');
await client.query('CREATE TABLE IF NOT EXISTS "_prisma_migrations" ("id" VARCHAR(36) PRIMARY KEY,"checksum" VARCHAR(64) NOT NULL,"finished_at" TIMESTAMPTZ,"migration_name" VARCHAR(255) NOT NULL,"logs" TEXT,"rolled_back_at" TIMESTAMPTZ,"started_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"applied_steps_count" INTEGER NOT NULL DEFAULT 0)');
for(const entry of fs.readdirSync('prisma/migrations',{withFileTypes:true}).filter(e=>e.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name))){const file=path.join('prisma/migrations',entry.name,'migration.sql');if(!fs.existsSync(file))continue;const sql=fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'');const checksum=createHash('sha256').update(sql).digest('hex');const existing=await client.query('SELECT checksum,finished_at,rolled_back_at FROM "_prisma_migrations" WHERE migration_name=$1',[entry.name]);const applied=existing.rows.find(r=>r.finished_at&&!r.rolled_back_at);if(applied){if(![checksum,createHash('sha256').update(sql.replace(/\r\n/g,'\n')).digest('hex'),createHash('sha256').update(sql.replace(/\r?\n/g,'\r\n')).digest('hex')].includes(applied.checksum))throw new Error('A migração aplicada '+entry.name+' difere do arquivo local.');console.log('Já aplicada: '+entry.name);continue;}if(existing.rows.some(r=>!r.finished_at&&!r.rolled_back_at))throw new Error('Há uma migração pendente de recuperação: '+entry.name);await client.query('BEGIN');try{await client.query(sql);await client.query('INSERT INTO "_prisma_migrations" (id,checksum,migration_name,started_at,finished_at,applied_steps_count) VALUES ($1,$2,$3,NOW(),NOW(),1)',[randomUUID(),checksum,entry.name]);await client.query('COMMIT');console.log('Aplicada: '+entry.name);}catch(error){await client.query('ROLLBACK');throw error;}}
console.log('Estrutura online atualizada.');}catch(e){console.error('Migração não concluída: '+e.message.replace(/postgres(?:ql)?:\/\/\S+/g,'[conexão]'));process.exitCode=1;}finally{try{await client.query('SELECT pg_advisory_unlock(61008004)')}catch{}await client.end()}})();

